title: Hello, world! I'm Wilber
description: Wilber's blog # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Wilber # add your name
author-img: avater.jpg # add your photo
about-author: Stay Hungry Stay Foolish # add description
social-twitter: jiweibo # add your Twitter handle
social-facebook: jiweibo # add your Facebook handle
social-github: jiweibo # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: jiweibo1028@outlook.com # add your Email address

# Disqus
discus-identifier: Wilber # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
